---
name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Install go
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: 'go.mod'
      - name: Run build script
        run: ./scripts/build
        shell: bash
      - run: ls bin

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls bin
