---
name: build-and-deploy

on:
  push:
    branches:    
      - build-and-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Install go
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: 'go.mod'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run build script
        run: ./scripts/build
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: package/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: anthonyenr1quez/local-path-provisioner:latest
